name: Terraform Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Ensures the workflow can request the ID token

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Login to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          environment: azurecloud
          auth-type: SERVICE_PRINCIPAL
          
      # Initialize Terraform
      - name: Terraform Init
        run: terraform init ./terraform

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false ./terraform

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve ./terraform
